TenuredCLOUD/Misery

.github/workflows/bom-check.yml

Workflow that checks for BOM ([Byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark)) characters on pull requests.

Workflow to check for BOM characters

---

.github/workflows/arma.yml
tools/config_style_checker.py
tools/setup.bat

- Checks for BOM, config style and HEMTT update bat file.

Add Arma Workflow

---

addons/generator/functions/fnc_powerNearby.sqf
addons/generator/functions/fnc_running.sqf
addons/invstat/functions/fnc_addBuffOrAilment.sqf
addons/invstat/functions/fnc_removeBuffOrAilment.sqf
addons/invstat/functions/fnc_status.sqf
addons/loot/functions/fnc_addBuilding.sqf
addons/temperature/functions/fnc_temperature.sqf

- Anything HEMTT suggests a better way to do, should fix the rest of the HEMTT complaints.

All - HEMTT Code suggestions

---

addons/ambient_animals/XEH_preInit.sqf
addons/artifacts/XEH_preInit.sqf
addons/client/XEH_preInit.sqf
addons/eru/XEH_preInit.sqf
addons/fear/XEH_postInit.sqf
addons/fire/XEH_preInit.sqf
addons/fuel/XEH_preInit.sqf
addons/gasmask/XEH_preInit.sqf
addons/geiger/XEH_preInit.sqf
addons/headlamp/XEH_preInit.sqf
addons/ims/XEH_preInit.sqf
addons/inventory/XEH_preInit.sqf
addons/loot/XEH_postInit.sqf
addons/persistency/XEH_preInit.sqf
addons/phantoms/XEH_preInit.sqf
addons/psyfield/XEH_preInit.sqf
addons/radiation/XEH_preInit.sqf
addons/rfdetecter/XEH_preInit.sqf
addons/survival/XEH_preInit.sqf
addons/temperature/XEH_preInit.sqf
addons/traders/XEH_preInit.sqf
addons/zinfect/XEH_preInit.sqf

- Anything that hasn't been altered yet shouldn't be running. Makes testing things we have touched easier.

Disable untouched components from running

---

addons/audio/XEH_preInit.sqf
addons/audio/initSettings.inc.sqf
addons/markers/CfgMarkers.hpp
addons/nofuel/functions/fnc_removeFuelSources.sqf

Fixes from testing - 1

---

.github/workflows/arma.yml

Remove BOM check from workflow, HEMTT does this now.

---

addons/common/functions/fnc_hasItem.sqf

- title
- Now includes headgear, vest, uniform, backpack & goggles.

Common - Expand hasItem to include gear

---

addons/buildex/functions/fnc_hasHammer.sqf
addons/buildex/functions/fnc_hasSledghammer.sqf
addons/common/functions/fnc_nearTreeAxe.sqf
addons/common/functions/fnc_nearTreeSaw.sqf
addons/crudemed/functions/fnc_stitchThreadAct.sqf
addons/fire/functions/fnc_campfireBig.sqf
addons/fire/functions/fnc_campfiresmall.sqf
addons/fire/functions/fnc_lightFire.sqf
addons/gasmask/functions/fnc_useEmptyGasmask.sqf
addons/geiger/functions/fnc_batteries.sqf
addons/headlamp/functions/fnc_batteries.sqf
addons/inventory/functions/fnc_selectAction.sqf
addons/llcontainer/functions/fnc_storeArtifact.sqf
addons/radio/functions/fnc_portableRadioBatteries.sqf
addons/rfdetecter/functions/fnc_batteries.sqf
addons/rfdetecter/functions/fnc_syncLoop.sqf
addons/temperature/functions/fnc_insulation.sqf
addons/useitem/functions/fnc_electricSawBatteries.sqf
addons/woodcollect/functions/fnc_chainsawFuel.sqf

- title
- rework of in items commands moving towards more streamlined checks using Mike's refactored hasItem function
- Also bringing some cleanup of previous CASE structured code in action checks

ALL-hasItem-rework

---

addons/fear/functions/fnc_cycle.sqf
addons/fire/functions/fnc_lightFire.sqf
addons/forage/functions/fnc_canForage.sqf
addons/invstat/functions/fnc_status.sqf
addons/temperature/functions/fnc_cold.sqf
addons/temperature/functions/fnc_effectiveTemperature.sqf
addons/temperature/functions/fnc_temperature.sqf
addons/temperature/functions/fnc_warmup.sqf

- Change Misery inside function check to BIS insideBuilding command
- Moved to insideBuilding BIS command and removed previous Misery inside checks for players
- Removed Under roof status buff from inventory UI / status updater

temperature-inside-checks

---

LICENSE.txt

- Add other collaborators to copyright holding of Misery

Update LICENSE.txt file

---

addons/actions/initSettings.inc.sqf
addons/ambient_animals/functions/fnc_Spawner.sqf
addons/ambient_animals/initSettings.inc.sqf
addons/audio/initSettings.inc.sqf
addons/common/initSettings.inc.sqf
addons/cooking/initSettings.inc.sqf
addons/crafting/initSettings.inc.sqf
addons/eru/initSettings.inc.sqf
addons/fear/initSettings.inc.sqf
addons/fishing/initSettings.inc.sqf
addons/food/initSettings.inc.sqf
addons/forage/initSettings.inc.sqf
addons/gasmask/initSettings.inc.sqf
addons/geiger/initSettings.inc.sqf
addons/ims/initSettings.inc.sqf
addons/inventory/initSettings.inc.sqf
addons/llcontainer/initSettings.inc.sqf
addons/mining/initSettings.inc.sqf
addons/nonvg/initSettings.inc.sqf
addons/phantoms/initSettings.inc.sqf
addons/psyfield/initSettings.inc.sqf
addons/radiation/initSettings.inc.sqf
addons/rfdetecter/initSettings.inc.sqf
addons/survival/initSettings.inc.sqf
addons/temperature/initSettings.inc.sqf
addons/traders/initSettings.inc.sqf
addons/watercollect/initSettings.inc.sqf
addons/woodcollect/initSettings.inc.sqf
addons/zinfect/initSettings.inc.sqf

- Rework initSettings.ini files to a more standardized structure...
- Rewrote CBA settings tags to be more structured & utilized QGVAR macro for more efficient / clean variables most should now be camelCased...

ALL initSettings rework

---

addons/common/functions/fnc_debugMessage.sqf
addons/common/initSettings.inc.sqf

- Debug mode changes from checkmark to list, 0 disabled, 1 systemChats and 2 is systemChat + RPT.

Common - Update/Improve debug

---

addons/common/CfgFactionClasses.hpp
addons/common/config.cpp
addons/common/initSettings.inc.sqf
addons/main/config.cpp
addons/main/script_mod.hpp

- Adds required addons to prevent updating base classes.
- Cleans up CfgFactionClasses a bit.
- Sets required version to Arma 2.18

Main / Common cleanup

---

addons/actions/initSettings.inc.sqf
addons/ambient_ai/initSettings.inc.sqf
addons/ambient_animals/initSettings.inc.sqf
addons/ambient_animals/script_component.hpp
addons/audio/initSettings.inc.sqf
addons/cooking/initSettings.inc.sqf
addons/crafting/initSettings.inc.sqf
addons/fear/initSettings.inc.sqf
addons/fishing/initSettings.inc.sqf
addons/food/initSettings.inc.sqf
addons/forestry/initSettings.inc.sqf
addons/gasmask/initSettings.inc.sqf
addons/hydrology/initSettings.inc.sqf
addons/inventory/initSettings.inc.sqf
addons/mining/initSettings.inc.sqf
addons/money/initSettings.inc.sqf
addons/nonvg/initSettings.inc.sqf
addons/phantoms/initSettings.inc.sqf
addons/radiation/initSettings.inc.sqf
addons/rfdetecter/initSettings.inc.sqf
addons/safezone/initSettings.inc.sqf
addons/survival/initSettings.inc.sqf
addons/temperature/initSettings.inc.sqf
addons/traders/initSettings.inc.sqf
addons/zinfect/initSettings.inc.sqf

- Fixed indentation so settings are no longer in the middle east.
- Categorised based on component name

All - Settings cleanup

---

addons/sleep/CfgEventHandlers.hpp
addons/sleep/XEH_PREP.hpp
addons/sleep/XEH_postInit.sqf
addons/sleep/config.cpp
addons/sleep/functions/fnc_hourSelected.sqf
addons/sleep/functions/fnc_processSleep.sqf
addons/sleep/functions/fnc_sleepAction.sqf
addons/sleep/functions/fnc_sleepCondition.sqf
addons/sleep/script_component.hpp

- Slight rework, has some ToDos requiring other components to be finished.

Improve - Sleep component

---

addons/medicine/functions/fnc_antibiotic.sqf
addons/medicine/functions/fnc_antiparasitic.sqf
addons/medicine/functions/fnc_caffetinTablets.sqf
addons/medicine/functions/fnc_cenestin.sqf
addons/medicine/functions/fnc_clozapine.sqf
addons/medicine/functions/fnc_clozapineInjection.sqf
addons/medicine/functions/fnc_painPill.sqf
addons/medicine/functions/fnc_randomPharm.sqf
addons/medicine/functions/fnc_sleepingPill.sqf
addons/medicine/functions/fnc_thbdInjection.sqf
addons/medicine/functions/fnc_thbdInjectionStim.sqf
addons/stims/functions/fnc_cocaine.sqf
addons/tobacco/functions/fnc_cigar.sqf
addons/tobacco/functions/fnc_cigarettes.sqf

- Was missing final parameter everywhere it was used. (Quantity)

Fix - All, Add missing parameter to ace function call

---

addons/artifacts/functions/fnc_spawn.sqf
addons/common/XEH_PREP.hpp
addons/common/functions/fnc_spawnLoot.sqf

- Shortened the function, same functionality.
- Created loot spawn function inside Common, can be used for most anything.

Improve - Artifacts, spawn function

---

addons/common/functions/fnc_getPlayerVariables.sqf
addons/persistence/script_component.hpp

Improve - Expand Persistence Variables

---

addons/alcohol/functions/fnc_beer.sqf
addons/alcohol/functions/fnc_vodka.sqf
addons/artifacts/functions/fnc_exposure.sqf
addons/common/functions/fnc_addStatusModifier.sqf
addons/gasmask/XEH_postInit.sqf
addons/gasmask/functions/fnc_deficiency.sqf
addons/gasmask/functions/fnc_useCartridges.sqf
addons/medicine/functions/fnc_clozapine.sqf
addons/medicine/functions/fnc_clozapineInjection.sqf
addons/psychosis/XEH_postInit.sqf
addons/psychosis/functions/fnc_loop.sqf
addons/radiation/XEH_postInit.sqf
addons/radiation/functions/fnc_process.sqf
addons/survival/XEH_postInit.sqf
addons/survival/functions/fnc_hungry.sqf
addons/survival/functions/fnc_loop.sqf
addons/temperature/functions/fnc_cold.sqf
addons/temperature/functions/fnc_coldPack.sqf
addons/temperature/functions/fnc_effectiveTemperature.sqf
addons/temperature/functions/fnc_heatPack.sqf
addons/temperature/functions/fnc_overtemp.sqf
addons/temperature/functions/fnc_sick.sqf
addons/temperature/functions/fnc_warmup.sqf
addons/temperature/functions/fnc_water.sqf
addons/tobacco/functions/fnc_cigar.sqf
addons/tobacco/functions/fnc_cigarettes.sqf

- Update to `addStatusModifier` function from common.
- Updates most variables in loops using above function.
- Rewrote some stuff to be better
- INDENTED THINGS CLOUD. **INDENTED.**

All - Update player variables on loop

---

addons/ui/menus/bank.hpp
addons/ui/menus/cooking.hpp
addons/ui/menus/crafting.hpp
addons/ui/menus/traderShop.hpp

- Math is already done before build time.
- Also formatting.

UI - Hemtt 1.15.0 suggestions

---

addons/assets/CfgMagazines.hpp
addons/assets/CfgWeapons.hpp
addons/assets/config.cpp

Fix - assets

---

addons/holster/$PBOPREFIX$
addons/holster/CfgEventHandlers.hpp
addons/holster/XEH_PREP.hpp
addons/holster/XEH_preInit.sqf
addons/holster/config.cpp
addons/holster/functions/fnc_action.sqf
addons/holster/initSettings.inc.sqf
addons/holster/script_component.hpp

- added new component "holster"
- added cba keybind for holstering weapons via currentWeapon check for players

Add - Holster

---

addons/assets/CfgVehicles.hpp
addons/forge/XEH_PREP.hpp
addons/forge/XEH_postInit.sqf
addons/forge/functions/fnc_burnFuel.sqf
addons/forge/functions/fnc_track.sqf

- Each forge that initialises will be added to the forge list, no more `allMissionObjects` .. hopefully. (If it doesn't work it needs CBA XEH)

Forge - Track forges with class event handler
